pages:
    stage: deploy
    before_script:
      - npm install
    script:
      - npm run build-storybook
      - mkdir .public
      - cp -r * .public
      - mv .public public
    artifacts:
      paths:
        - public
    only:
      - develop